### ISSUE TITLE
Sorting & Getting Keys

### ISSUE THREAD

**Issue by phidias51** [PolymerEl/firebase-nest#2]
Suppose you have a series of "friends" (basically bookmarked users as shown below). How do you sort those users? I tried providing the dom-repeat template with a comparator but that doesn't work.  

```
<firebase-auth app-name="myapp" user="{{user}}"></firebase-auth>
        <firebase-nest app-name="myapp" path="/user-contact/[[user.uid]]" data="{{data}}" allow-sync="true">
            <template is="dom-repeat" items="[[data]]" as="contact" sort="_contactSorter">
            <firebase-value app-name="myapp" value="{{contact}}" key="$key" data="{{contactData}}" path="/users/[[contact.$key]]" ></firebase-value>
            <ver-contact-card class="card" id="[[contact.$key]]" model="{{contact}}"></ver-contact-card>
            </template>
        </firebase-nest>

```

The other problem I have with the above code, is that I can't seem to get the key for each contact. It always comes back "undefined" which is really strange given that you have to have the **contact.$key** in order to do the lookup query.  The query returns the other user data just fine, but not the key.

**Comment by christophe-g** [comment]
Thanks for submitting this first issue. I used it to do a bit of clean-up for this component (tag 0.6.0) ...

First, please note that `<firebase-nest>` relies on yet unmerged PR to polymerfire, most importantly this one, https://github.com/firebase/polymerfire/pull/234 (but also https://github.com/firebase/polymerfire/pull/230 for performance and https://github.com/firebase/polymerfire/pull/235). Those are merged under https://github.com/christophe-g/polymerfire#dev.

Part of the issues you are seing might be related to this (especially the `undefined` problem).  Sorting (either using firebase-query sorting features or  dom-repeat sort function) should work as usual. 

if your version of the markup still does not work , you can try it this way: 
```html
 <template is="dom-repeat" items="{{data}}" as="contact" sort="_contactSorter">
            <firebase-value app-name="myapp"  key="_contact" data="{{item}}" path="/users/[[item.$key]]" ></firebase-value>
            <ver-contact-card class="card" id="[[item.$key]]" model="{{items._contact}}"></ver-contact-card>
            </template>
```

**Comment by phidias51** [comment]
Thanks for implementing some fixes. I assume that I'll need to wait for the PRs to be merged before I can try them out.

**Comment by christophe-g** [comment]
Alternatively, `bower install https://github.com/christophe-g/polymerfire#dev` to try it out.

**Comment by phidias51** [comment]
Looks like there are some conflicts with your PRs.
